### ISSUE TITLE
VerbForm missing

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/UD_Bulgarian#2]
According to [svalidation](http://universaldependencies.org/svalidation.html#verb-lacks-the-verbform-feature), all verbs should be further categorized using the [VerbForm](http://universaldependencies.org/u/feat/VerbForm.html) feature.
Currently, there are 149 cases of upos=VERB without VerbForm.

I guess, this could be fixed automatically, using the original tag (e.g xtag=`Vpptf-o3s`), possibly using the recommendations for Bulgarian in @dan-zeman's [paper](https://ufal.mff.cuni.cz/pbml/105/art-zeman.pdf) and [conversion rules](http://universaldependencies.org/tagset-conversion/bg-conll-uposf.html).

If it is not easily possible, feel free to close this issue.

**Comment by martinpopel** [comment]
See a [search query result](http://ufallab.ms.mff.cuni.cz/~popel/bg/bug-no-verbform.html) with all such verbs without VerbForm highlighted (train and dev sets concatenated, test set excluded).

**Comment by KirilSimov** [comment]
Dear Martin,

Thank you very much for your emails.
One question is how we could edit the problematic cases?
Directly in the the repository, or locally here and then to upload
the new version?
I am sorry if you already answer this question in the previous messages.

With best regards,

Kiril

From: Martin Popel 
Sent: Monday, February 6, 2017 2:40 PM
To: UniversalDependencies/UD_Bulgarian 
Cc: Subscribed 
Subject: [UniversalDependencies/UD_Bulgarian] VerbForm missing (#2)

According to svalidation, all verbs should be further categorized using the VerbForm feature.
Currently, there are 149 cases of upos=VERB without VerbForm.

I guess, this could be fixed automatically, using the original tag (e.g xtag=Vpptf-o3s), possibly using the recommendations for Bulgarian in @dan-zeman's paper and conversion rules.

If it is not easily possible, feel free to close this issue.

**Comment by osenova** [comment]
Hi Martin,

Kiril discovered that all the features are missing (not only VerbForm), so he did a file with substitutions. Please see the attached file whether is is OK for you to substitute, or we should do that. Thanks!

===============

The rules for the substitutions of old FEATS values with new FEATS values
are represented as rows in a table.

The first three columns corresponds to the columns:

UPOSTAG    XPOSTAG    FEATS in CONLLU

the new value is in the fourth column (named in the table as NEWFEATS).

If it is easy to substitute in your system it will be very good, if not we 
could do
here.

[bg-new-feat-01.txt](https://github.com/UniversalDependencies/UD_Bulgarian/files/756939/bg-new-feat-01.txt)

**Comment by jnivre** [comment]
Can't you just push a new version of the data to the repository?

**Comment by martinpopel** [comment]
@jnivre I will push the new version soon. I have converted the data with [Convert1to2](https://github.com/udapi/udapi-python/tree/master/udapi/block/ud), so there will be more changes, not only added FEATS.

**Comment by martinpopel** [comment]
I've pushed the new version, so Bulgarian now passes [validate.py](http://universaldependencies.org/validation.html).

@osenova, @KirilSimov:
> Kiril discovered that all the features are missing (not only VerbForm)

No, most features are there (both, in your original xml data and in my converted conllu). VerbForm is present with most verbs, only some verbs miss this feature.

> so he did a file with substitutions. 

This file misses features exactly for those tags which are missing in the data. So this file does not help.
I will try to implement a converter using http://www.bultreebank.org/TechRep/BTB-TR03.pdf

**Comment by KirilSimov** [comment]
Dear Martin,
I could do the substitution by myself. I will use the version in the repository, but I need also the test part of the treebank. Could you send it to me?
I just discover some more cases where to improve the features..
With best regards,

Kiril

**Comment by martinpopel** [comment]
http://ufallab.ms.mff.cuni.cz/~popel/bg/bg-ud-test-final.conllu
