### ISSUE TITLE
PronType missing

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/UD_Bulgarian#3]
According to [svalidation](http://universaldependencies.org/svalidation.html#pron-or-det-lacks-the-prontype-feature), all pronouns and determiners should be further categorized using the [PronType](http://universaldependencies.org/u/feat/PronType.html) feature. 
Currently, there are [144 cases](http://ufallab.ms.mff.cuni.cz/~popel/bg/bug-no-prontype.html) of upos=DET|PRON without PronType.

**Comment by martinpopel** [comment]
In the UDv2 version, there are just [18 cases](http://ufallab.ms.mff.cuni.cz/~popel/bg/bugs.html) of missing PronType (plus 6 missing VerbForm and 24 missing NumType, see #2 and #4).

**Comment by KirilSimov** [comment]
Dear Martin,

Here are the correspondences for these problematic cases:

================
PronType (full list of features):

Pic -> PronType=Int
Pce-op -> Case=Nom|Number=Plur|PronType=Tot
Pde-os-n -> Case=Nom|Gender=Neut|Number=Sing|PronType=Dem
Pfp--p -> Number=Plur|PronType=Ind

VerbFrom:

Vpptcv--smi -> Aspect=Perf|Definite=Ind|Gender=Masc|Number=Sing|VerbForm=Part|Voice=Pass
Vxitu-o3s -> Aspect=Imp|Mood=Cnd|Number=Sing|Person=3|Tense=Past|VerbForm=Fin
Vpptcv--p-d -> Aspect=Perf|Definite=Def|Degree=Pos|Number=Plur|VerbForm=Part|Voice=Pass

NumType:

# sent_id = Novinar-2000-11-16-s53
# text = Според него сегашните цени от около $ 34 - 35 за барел са твърде високи и САЩ биха предпочели те да варират около 20 - 25 долара.
8    34    34-35    NUM    Mc-pi    Definite=Ind|Number=Plur|NumType=Card    7    nummod    _    _
9    -    _    NUM    Mc-pi    _    8    goeswith    _    _
10    35    _    NUM    Mc-pi    _    8    goeswith    _    _

Kiril: Here we suggest to repeat the same features like for token 8. It is a little strange to have Num for "-". If not a problem it can be with features for punctuation


# sent_id = Sega-2000-08-03-s455
# text = 02.08.2000 Футбол - фенове на "Бешикташ" загряват пред джамията в центъра на София преди мача.
1    02    02    NUM    M    _    13    discourse    _    SpaceAfter=No
2    .    .    PUNCT    punct    _    1    punct    _    SpaceAfter=No
3    08    08    NUM    M    _    1    conj    _    SpaceAfter=No
4    .    .    PUNCT    punct    _    1    punct    _    SpaceAfter=No
5    2000    2000    NUM    M    _    1    conj    _    _

Num-Type=Ord for 1,3 and 5
================

The question is how to correct them? We to do this here, or you prefer something else?
I think we to do is better.

With best regards,

Kiril

**Comment by martinpopel** [comment]
Fixed in UDv2
